# Generated by Django 4.1.6 on 2023-02-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mobileNumber', models.IntegerField()),
                ('dob', models.DateField()),
                ('profilePhoto', models.FileField(default=None, upload_to='images')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('playlists', models.ManyToManyField(to='song.playlist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
