# Generated by Django 4.1.6 on 2023-02-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_alter_podcast_comments_alter_podcast_size_and_more'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='playlists',
            field=models.ManyToManyField(blank=True, to='song.playlist'),
        ),
    ]
