# Generated by Django 4.1.6 on 2023-03-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_users_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='mobileNumber',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
    ]
