# Generated by Django 4.1.6 on 2023-02-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_playlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePhoto',
            field=models.FileField(blank=True, default=None, upload_to='images'),
        ),
    ]
