# Generated by Django 4.1.6 on 2023-02-20 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_profilephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobileNumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profilePhoto',
        ),
    ]
