# Generated by Django 4.1.6 on 2023-03-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_users_email_remove_users_mobilenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profilePhoto',
            field=models.FileField(default=None, upload_to='images'),
        ),
    ]
