# Generated by Django 4.1.6 on 2023-02-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_user_dob_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePhoto',
            field=models.FileField(blank=True, default=None, upload_to='images'),
        ),
    ]
