# Generated by Django 4.1.6 on 2023-03-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_users_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profilePhoto',
            field=models.FileField(blank=True, default=None, upload_to='images'),
        ),
    ]
