# Generated by Django 4.1.6 on 2023-02-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_profilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, default='2023-02-15'),
        ),
    ]
