# Generated by Django 4.1.6 on 2023-03-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_users_email_users_mobilenumber_users_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='playlists',
        ),
    ]
