# Generated by Django 4.1.6 on 2023-02-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='patel@g.com', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='mobileNumber',
            field=models.IntegerField(default='10011001'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='hi', max_length=255),
        ),
    ]
