# Generated by Django 4.1.6 on 2023-02-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_alter_podcast_comments_alter_podcast_size_and_more'),
        ('login', '0008_alter_user_dob_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
