# Generated by Django 4.1.6 on 2023-03-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='totalSongs',
        ),
    ]
