# Generated by Django 4.1.6 on 2023-02-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='comments',
            field=models.ManyToManyField(blank=True, to='song.comment'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='comments',
            field=models.ManyToManyField(blank=True, to='song.comment'),
        ),
        migrations.AlterField(
            model_name='song',
            name='size',
            field=models.FloatField(),
        ),
    ]
