# Generated by Django 4.1.6 on 2023-03-13 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_remove_playlist_totalsongs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='song.song'),
        ),
    ]
