# Generated by Django 4.1.6 on 2023-03-13 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_remove_playlist_songs_playlist_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='song.song'),
        ),
    ]
