# Generated by Django 4.1.6 on 2023-03-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remove_users_playlists'),
        ('song', '0005_remove_playlist_songs_playlist_songs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
