# Generated by Django 4.1.7 on 2023-03-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_remove_podcast_duration_remove_song_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='size',
        ),
        migrations.RemoveField(
            model_name='song',
            name='size',
        ),
    ]
